server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: marebito7
    #강남 YMCA
    password: ENC(YVtXsaFqMCPJUIfI7IWdJjw3vJsf3oKh)
    url: jdbc:mariadb://marebito7.cafe24.com:3306/marebito7
    initialization-mode: embedded
    platform: mariadb
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true

service:
  upload-file-path: D:\workSpace\disk\file
  upload-image-path: D:\workSpace\disk\image
  upload-temp-path: D:\workSpace\disk\temp

logging:
  file:
    path: D:\workSpace\logs
  config: classpath:logback-local.xml