server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: marebito7
      password: ENC(YVtXsaFqMCPJUIfI7IWdJjw3vJsf3oKh)
      url: jdbc:mariadb://localhost:3306/marebito7

logging:
  file:
    path: /marebito7/logs
  config: classpath:logback-${spring.profiles.active}.xml


app:
  file-upload-storage:
    root: /marebito7/upload
    notice: ${app.file-upload-storage.root}/notice
    product: ${app.file-upload-storage.root}/product
    temp: ${app.file-upload-storage.root}/temp
    carousel: ${app.file-upload-storage.root}/carousel
    content: ${app.file-upload-storage.root}/content
