server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: marebito7
    #강남 YMCA
    password: ENC(YVtXsaFqMCPJUIfI7IWdJjw3vJsf3oKh)
    url: jdbc:mariadb://localhost:3306/marebito7
    initialization-mode: embedded
    platform: mariadb
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true

service:
  upload-file-path: /marebito7/upload/file
  upload-image-path: /marebito7/upload/image
  upload-temp-path: /marebito7/upload/temp

logging:
  file:
    path: /marebito7/logs
  config: classpath:logback-${spring.profiles.active}.xml