server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: roywmc
    password: dldydwns32@
    url: jdbc:mariadb://localhost:3306/roywmc
    initialization-mode: embedded
    platform: mariadb
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB10Dialect
        format_sql: true

service:
  upload-file-path: /roywmc/upload/file
  upload-image-path: /roywmc/upload/image
  upload-temp-path: /roywmc/upload/temp