server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: roywmc
      password: dldydwns2..
      #jdbc-url: jdbc:mariadb://roywmc.cafe24.com:3306/roywmc
      jdbc-url: jdbc:mariadb://localhost:3306/roywmc

logging:
  file:
    path: ${user.home}\workSpace\logs
  config: classpath:logback-local.xml

debug: true