server:
  port: 8080
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: true
    include-exception: true

spring:
  application:
    name: utour-api
  messages:
    basename: messages
  servlet:
    multipart:
      max-file-size: 33MB
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
  cache:
    jcache:
      config: classpath:ehcache.xml
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES

app:
  login:
    secret-key: utour
  delete-temp-file:
    storage-period: 7
    limit: 100
