server:
  port: 8080
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: true
    include-exception: true

spring:
  application:
    name: utour
  messages:
    basename: messages
  servlet:
    multipart:
      max-file-size: 20MB
jasypt:
  encryptor:
    bean: jasyptStringEncryptor