server:
  port: 8080
  servlet:
    context-path: /api
  error:
    whitelabel:
      enabled: true
    include-exception: true

spring:
  application:
    name: utour-api
  messages:
    basename: messages
  servlet:
    multipart:
      max-file-size: 33MB
  jackson:
    property-naming-strategy: SNAKE_CASE

jasypt:
  encryptor:
    bean: jasyptStringEncryptor