server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: marebito6
      password: ENC(9IizH6fff/gXAx38j9hjO8Gl4bHnIEmZ)
      url: jdbc:mariadb://localhost:3306/marebito6

logging:
  file:
    path: /marebito6/logs
  config: classpath:logback-local.xml

debug: true

app:
  file-upload-storage:
    root: /marebito6/upload
    notice: ${app.file-upload-storage.root}/notice
    product: ${app.file-upload-storage.root}/product
    temp: ${app.file-upload-storage.root}/temp
    carousel: ${app.file-upload-storage.root}/carousel
    content: ${app.file-upload-storage.root}/content
