spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: roywmc
      password: dldydwns2..
      jdbc-url: jdbc:log4jdbc:mariadb://roywmc.cafe24.com:3306/roywmc
      maximum-pool-size: 10
      minimum-idle: 5
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:sql/schema-local.sql
      data-locations: classpath:sql/data-local.sql

debug: true

logging:
  file:
    path: ${user.home}\workSpace\logs
  config: classpath:logback-local.xml
  pattern:
    console:

app:
  file-upload-storage:
    root: ${user.home}/.upload
    notice: ${app.file-upload-storage.root}/notice
    product: ${app.file-upload-storage.root}/product
    temp: ${app.file-upload-storage.root}/temp
    carousel: ${app.file-upload-storage.root}/carousel
